In [5]:
import h5py
from utils.tools import SimpleImageViewer

In [6]:
h5_file_path = 'data/bedroom_04.h5'
h5_file      = h5py.File(h5_file_path, 'r')

In [4]:
view = SimpleImageViewer()

In [10]:
view.imshow(h5_file['observation'][1])

In [13]:
len(h5_file['resnet_feature'][26])

10

In [14]:
len(h5_file['resnet_feature'][28])

10

In [15]:
len(h5_file['resnet_feature'][287])

10

In [27]:
import numpy as np

In [18]:
h5_file['resnet_feature'][287][0][:,np.newaxis]

array([[0.08918659],
       [1.9223003 ],
       [0.21887285],
       ...,
       [0.3097535 ],
       [0.43626192],
       [0.32121357]], dtype=float32)

In [19]:
h5_file['rotation'][287]

270

In [20]:
h5_file['rotation'][60]

0

In [22]:
h5_file['rotation'][286]

180

In [23]:
h5_file['rotation'][285]

90

In [24]:
h5_file['rotation'][284]

0

In [25]:
h5_file['location'][284]

array([8., 5.])

In [26]:
h5_file['location'][285]

array([8., 5.])

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])